providers = ["java"]

[phases.setup]
nixPkgs = ["...", "jdk21"]

[phases.build]
cmds = ["mvn clean package -DskipTests"]

[phases.deploy]
cmds = ["java -Dserver.port=$PORT -jar target/cardapio-digital-1.0.0.jar"]

[start]
cmd = "java -Dserver.port=$PORT -jar target/cardapio-digital-1.0.0.jar"
